version: '3.7'

services:
  rabbit-seed:
    image: rabbitmq:management-alpine
    hostname: "rabbit-seed"
    expose:
      - "4369"
      - "5672"
      - "15672"
      - "25672"
    volumes:
      - ./rabbit.conf:/config/rabbit.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbit.conf
      - RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics -q check_running || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  rabbit-slave:
    image: rabbitmq:management-alpine
    hostname: "rabbit-slave"
    expose:
      - "4369"
      - "5672"
      - "15672"
      - "25672"
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./rabbit.conf:/config/rabbit.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbit.conf
      - RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW
      - CLUSTER_SEED=rabbit@rabbit-seed
    entrypoint: /usr/local/bin/entrypoint.sh
    depends_on:
      rabbit-seed:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics -q check_running || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 10s

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      rabbit-seed:
        condition: service_healthy
    ports:
      - "4000:4000"
