version: '3.7'

services:
  rabbit-seed:
    image: rabbitmq:management-alpine
    hostname: "rabbit-seed"
    volumes:
      - ./rabbit.conf:/config/rabbit.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbit.conf
    healthcheck:
      &hc
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics -q check_running || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  rabbit-worker:
    image: rabbitmq:management-alpine
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./rabbit.conf:/config/rabbit.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbit.conf
      - CLUSTER_SEED=rabbit@rabbit-seed
    entrypoint: /usr/local/bin/entrypoint.sh
    depends_on:
      rabbit-seed:
        condition: service_healthy
    healthcheck: *hc
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      rabbit-seed:
        condition: service_healthy
    ports:
      - "4000:4000"
