version: '3.7'

services:
  rabbit-1:
    &rabbit
    image: rabbitmq:management-alpine
    hostname: "rabbit-1"
    expose:
      - "4369"
      - "5672"
      - "15672"
      - "25672"
    volumes:
      - ./rabbit.conf:/config/rabbit.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbit.conf
      - RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics -q check_running || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  rabbit-2:
    &rabbit2
    <<: *rabbit
    hostname: "rabbit-2"
    depends_on:
      rabbit-1:
        condition: service_healthy

  rabbit-3:
    <<: *rabbit2
    hostname: "rabbit-3"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      rabbit-1:
        condition: service_healthy
    ports:
      - "4000:4000"
